build:
	docker build -t xmake-remote-cache .

run:
	docker run --rm --name xmake-remote-cache -it xmake-remote-cache:latest

# stop-container:
# 	docker container stop xmake-remote-cache

# rm-container: stop-container
# 	docker container rm xmake-remote-cache

rm-image:
	docker image rm xmake-remote-cache:latest
